version: '3.1'
services:
    mytest:
        build:
            context: ./
            dockerfile: Dockerfile
        image: mytest:v2.0.0
        container_name: mytest
        ports:
            - 3000:3000
